name: Deployment
on:
  push:
    branches:
      - "master"

jobs:
  dockerize:
    name: Dockerize
    runs-on: ubuntu-latest
    env:
      DO_PASSWORD: ${{ secrets.DO_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 459672519579.dkr.ecr.us-east-1.amazonaws.com
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Build, tag and push
        run: |
          cd build
          docker build -t bookstore-api .
          docker tag bookstore-api:latest 459672519579.dkr.ecr.us-east-1.amazonaws.com/bookstore-api:latest
          docker push 459672519579.dkr.ecr.us-east-1.amazonaws.com/bookstore-api:latest
